<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'bn_name' => 'ড্যাশবোর্ড',
                'created_at' => '2023-03-19 14:04:30',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => 'uil-home-alt',
                'id' => 1,
                'is_hidden' => 'No',
                'name' => 'Dashboard',
                'order_by' => 4,
                'parent_id' => NULL,
                'route_name' => 'dashboard',
                'status' => 1,
                'system_name' => 'Dashboard',
                'updated_at' => '2023-04-03 10:38:48',
                'updated_by' => 1,
            ),
            1 => 
            array (
                'bn_name' => 'ইউজার ম্যানেজমেন্ট',
                'created_at' => '2023-03-19 18:06:39',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 2,
                'is_hidden' => 'No',
                'name' => 'User Management',
                'order_by' => 5,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'User Management',
                'updated_at' => '2023-04-03 10:38:48',
                'updated_by' => 1,
            ),
            2 => 
            array (
                'bn_name' => 'ইউজার',
                'created_at' => '2023-03-19 18:08:09',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 3,
                'is_hidden' => 'No',
                'name' => 'User',
                'order_by' => 1,
                'parent_id' => 2,
                'route_name' => 'user.index',
                'status' => 1,
                'system_name' => 'User',
                'updated_at' => '2023-03-31 18:10:57',
                'updated_by' => 1,
            ),
            3 => 
            array (
                'bn_name' => 'রোল ম্যানেজমেন্ট',
                'created_at' => '2023-03-19 18:14:26',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 4,
                'is_hidden' => 'No',
                'name' => 'Role Management',
                'order_by' => 6,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Role Management',
                'updated_at' => '2023-04-03 10:38:48',
                'updated_by' => 1,
            ),
            4 => 
            array (
                'bn_name' => 'রোল',
                'created_at' => '2023-03-19 18:17:21',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 5,
                'is_hidden' => 'No',
                'name' => 'Role',
                'order_by' => 1,
                'parent_id' => 4,
                'route_name' => 'role.index',
                'status' => 1,
                'system_name' => 'Role',
                'updated_at' => '2023-03-31 18:11:32',
                'updated_by' => 1,
            ),
            5 => 
            array (
                'bn_name' => 'মেন্যু ম্যানেজমেন্ট',
                'created_at' => '2023-04-03 10:38:48',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 25,
                'is_hidden' => 'No',
                'name' => 'Menu Management',
                'order_by' => 1,
                'parent_id' => NULL,
                'route_name' => '',
                'status' => 1,
                'system_name' => 'Menu Management',
                'updated_at' => '2023-04-03 10:38:48',
                'updated_by' => 1,
            ),
            6 => 
            array (
                'bn_name' => 'মেন্যু',
                'created_at' => '2023-04-03 10:39:32',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 26,
                'is_hidden' => 'No',
                'name' => 'Menu',
                'order_by' => 1,
                'parent_id' => 25,
                'route_name' => 'menu.index',
                'status' => 1,
                'system_name' => 'Menu',
                'updated_at' => '2023-04-03 10:39:32',
                'updated_by' => 1,
            ),
            7 => 
            array (
                'bn_name' => 'আমাদের সম্পর্কে',
                'created_at' => '2023-06-11 13:35:23',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 27,
                'is_hidden' => 'No',
                'name' => 'About Institute',
                'order_by' => 10,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'About Institute',
                'updated_at' => '2023-06-11 13:35:23',
                'updated_by' => 1,
            ),
            8 => 
            array (
                'bn_name' => 'পেইজ',
                'created_at' => '2023-06-11 13:35:49',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 28,
                'is_hidden' => 'No',
                'name' => 'Pages',
                'order_by' => 1,
                'parent_id' => 27,
                'route_name' => 'pages.index',
                'status' => 1,
                'system_name' => 'Pages',
                'updated_at' => '2023-06-11 13:36:35',
                'updated_by' => 1,
            ),
            9 => 
            array (
                'bn_name' => 'প্রশাসনিক তথ্য',
                'created_at' => '2023-06-11 13:37:43',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 29,
                'is_hidden' => 'No',
                'name' => 'Administrator Info.',
                'order_by' => 11,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Administrator Info.',
                'updated_at' => '2023-06-11 13:37:43',
                'updated_by' => 1,
            ),
            10 => 
            array (
                'bn_name' => 'অধ্যক্ষ/সভাপতি',
                'created_at' => '2023-06-11 13:38:49',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 30,
                'is_hidden' => 'No',
                'name' => 'Principle/President',
                'order_by' => 1,
                'parent_id' => 29,
                'route_name' => 'principle.index',
                'status' => 1,
                'system_name' => 'Principle',
                'updated_at' => '2023-06-11 13:39:21',
                'updated_by' => 1,
            ),
            11 => 
            array (
                'bn_name' => 'গ্যালারি',
                'created_at' => '2023-06-11 13:54:20',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 31,
                'is_hidden' => 'No',
                'name' => 'Gallery',
                'order_by' => 22,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Gallery',
                'updated_at' => '2023-06-11 14:09:21',
                'updated_by' => 1,
            ),
            12 => 
            array (
                'bn_name' => 'ফটো গ্যালারি',
                'created_at' => '2023-06-11 13:54:53',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 32,
                'is_hidden' => 'No',
                'name' => 'Photo Gallary',
                'order_by' => 1,
                'parent_id' => 31,
                'route_name' => 'photogallerys.index',
                'status' => 1,
                'system_name' => 'Photo Gallary',
                'updated_at' => '2023-06-11 13:54:53',
                'updated_by' => 1,
            ),
            13 => 
            array (
                'bn_name' => 'ভিডিও গ্যালারি',
                'created_at' => '2023-06-11 13:55:31',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 33,
                'is_hidden' => 'No',
                'name' => 'Video Gallary',
                'order_by' => 2,
                'parent_id' => 31,
                'route_name' => 'videogallerys.index',
                'status' => 1,
                'system_name' => 'Video Gallary',
                'updated_at' => '2023-06-11 13:55:31',
                'updated_by' => 1,
            ),
            14 => 
            array (
                'bn_name' => 'নোটিশ',
                'created_at' => '2023-06-11 14:01:55',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 34,
                'is_hidden' => 'No',
                'name' => 'Notices',
                'order_by' => 12,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Notices',
                'updated_at' => '2023-06-11 14:01:55',
                'updated_by' => 1,
            ),
            15 => 
            array (
                'bn_name' => 'নোটিশ',
                'created_at' => '2023-06-11 14:02:50',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 35,
                'is_hidden' => 'No',
                'name' => 'Notices',
                'order_by' => 1,
                'parent_id' => 34,
                'route_name' => 'notices.index',
                'status' => 1,
                'system_name' => 'Notices',
                'updated_at' => '2023-06-11 14:02:50',
                'updated_by' => 1,
            ),
            16 => 
            array (
                'bn_name' => 'লিংক',
                'created_at' => '2023-06-11 14:09:21',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 36,
                'is_hidden' => 'No',
                'name' => 'Useful Link',
                'order_by' => 19,
                'parent_id' => NULL,
                'route_name' => NULL,
                'status' => 1,
                'system_name' => 'Useful Link',
                'updated_at' => '2023-06-11 14:09:21',
                'updated_by' => 1,
            ),
            17 => 
            array (
                'bn_name' => 'লিংক',
                'created_at' => '2023-06-11 14:09:57',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 37,
                'is_hidden' => 'No',
                'name' => 'Link',
                'order_by' => 1,
                'parent_id' => 36,
                'route_name' => 'usefullink.index',
                'status' => 1,
                'system_name' => 'Link',
                'updated_at' => '2023-06-11 14:09:57',
                'updated_by' => 1,
            ),
            18 => 
            array (
                'bn_name' => 'সদস্য যোগ করুন',
                'created_at' => '2023-06-11 14:28:27',
                'created_by' => 1,
                'deleted_at' => NULL,
                'deleted_by' => NULL,
                'icon' => NULL,
                'id' => 38,
                'is_hidden' => 'No',
                'name' => 'Add Members',
                'order_by' => 2,
                'parent_id' => 29,
                'route_name' => 'members.index',
                'status' => 1,
                'system_name' => 'Add Members',
                'updated_at' => '2023-06-11 14:28:27',
                'updated_by' => 1,
            ),
        ));
        
        
    }
}